
apiVersion: networking.istio.io/v1alpha3
kind: Gateway # configure egressgateway to forward to ECB 
metadata:
  name: istio-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - www.ecb.europa.eu
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService # direct ECB traffic through the secure gateway 
metadata:
  name: direct-ecb-through-egress-gateway
spec:
  hosts:
  - www.ecb.europa.eu
  gateways:
  - istio-egressgateway
  - mesh
  http:
  - match:
    - gateways:
      - mesh # CurrencyService --> EgressGateway 
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: ecb
        port:
          number: 80
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway # EgressGateway --> ECB External
      port: 80
    route:
    - destination:
        host: www.ecb.europa.eu
        port:
          number: 80
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule #define a subset 
metadata:
  name: egressgateway-for-ecb
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: ecb